services:
  db:
    build: .
    container_name: bmi_app-db_container
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bmi_database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3307:3306
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - my-vol:/var/lib/mysql
volumes:
  my-vol:
